table inet mihomo {
    set bypass_v4 {
        type ipv4_addr
        flags interval
        elements = {
            0.0.0.0/8,
            10.0.0.0/8,
            100.64.0.0/10,
            127.0.0.0/8,
            169.254.0.0/16,
            172.16.0.0/12,
            192.0.0.0/24,
            192.168.0.0/16,
            198.18.0.0/15,
            224.0.0.0/4,
            240.0.0.0/4
        }
    }
    
    chain mangle_prerouting {
        type filter hook prerouting priority mangle - 1; policy accept;
        
        iifname != "br-lan" return
        meta mark 0xff return
        ip daddr @bypass_v4 return
        udp dport 53 return
        tcp dport 53 return
        
        meta l4proto tcp meta mark set 1 tproxy ip to 127.0.0.1:7893 accept
        meta l4proto udp meta mark set 1 tproxy ip to 127.0.0.1:7893 accept
    }
}
